kind: pipeline
name: deploy-docker

steps:
- name: create-docker-container
  image: plugins/docker
  privileged: true
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  commands:
  - docker ps