kind: pipeline
name: default

steps:
- name: test-docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t latest

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock