kind: pipeline
type: docker
name: default

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

steps:
  - name: build-image
    image: docker:latest
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - sleep 5
      - docker build -t my_future:latest .

  - name: run-container
    image: docker:latest
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - sleep 5
      - docker stop my_future || true
      - docker rm my_future || true
      - docker run -d --network Animalgeek-net --name my_future my_future:latest
      
  - name: run-clear-images
    image: docker:latest
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - docker image prune --all --force
