kind: pipeline
type: docker
name: default

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

steps:
  - name: build-image
    image: docker:latest
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - sleep 5
      - docker build -t mi-imagen:latest .

  - name: run-container
    image: docker:latest
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - sleep 5
      - docker stop contenedor-c || true
      - docker rm contenedor-c || true
      - docker run -d --name contenedor-c mi-imagen:latest
