kind: pipeline
type: docker
name: default

steps:
  - name: build-image
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t my_future:latest .

  - name: run-container
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker stop contenedor-c || true
      - docker rm contenedor-c || true
      - docker run -d --name contenedor-c my_future:latest
