kind: pipeline
name: deploy-docker

steps:
- name: test 1
  commands:
  - ls /

steps:
- name: create-docker-container
  image: plugins/docker
  privileged: true
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  commands:
  - docker ps

services:
  docker:
    image: docker:dind
    command: [ "--storage-driver=vfs", "--tls=false" ]
    privileged: true